{% set name = "colicoords" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cd73c5defcc747aaa436e6bb13c6732f130298a4f4cc9f790fe16c075980c29

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - pbr >=1.9
  run:
    - python >=3.6
    - numpy
    - matplotlib >=2.2.0
    - seaborn
    - mahotas
    - multiprocess
    - scipy
    - h5py
    - tifffile
    - tqdm >=4.27.0
    - symfit >=0.4.6
    - ipywidgets
    - IPython

test:
  imports:
    - colicoords

about:
  home: https://github.com/Jhsmit/ColiCoords
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Single-cell fluorescence microscopy data analysis
  doc_url: https://colicoords.readthedocs.io/
  dev_url: https://github.com/Jhsmit/ColiCoords

extra:
  recipe-maintainers:
    - jhsmit
