appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cBXF+w6TdVZElmP4SE/VuksqwdIZ+67kM3FWmfUTeJJx+Hvhw8aKYojCWCtoNDFpNmMdFoWi0cX+7RB+sV3YMwGjUDm8zsNckF3KdwY8Mf0yv+eorXXcKoxR3LpKPxLe42Z/ktkyhpursLiR0x3D4sQxXhbuLCTzaM0fDJB8/3UWj/xelMpJbMJoFu9HkqQGUwmPukVo9ovsQ7LZb0cVzhoVJxYgzYvzNRib72HHicOeyYxKfcT96dr9wxaFMqpEPJ3Gq/ALtZ87BRSaMwj4O3GoX3mhmwr1ekHT/3+kcc88SLhWb4cXgn+x+/RwCCRs2xeeg9GJe8RvkLgED2H3iqR6BFv0mo8dkAX597bSvQTptbqux0JwIN+AmjOHgM83p5kNljWlh6WOJc51QiB8jZf4P7fq6fe9mJH7s7bbE5dgrZVfb8H0QUCfvfEcCU2OSV4V1Are1ALIWnxOvZzsomLxGYHfj9dCfWMuf3cOckZvmfrcUfYgOc/ePIme717XCc7FhM3hf1nR5mXBX7AizbOfV6el4VMIBa8Fkh7Tb4zOj/sxHKqOhmifykjwqNYvofJKsP61tXG0meRtrRoVMoCaliNUFJotjthiL+LU7IgU8AltpzVtMRB9yJOQB87CoAemi6ioBoHPhE1Su9eWz3c/B97MLhcz9DIhmsbm+4c=}
provider:
  win: azure
conda_forge_output_validation: true
